export { TreatmentHero } from "./TreatmentHero";
export { PageHero } from "./PageHero";
export { TreatmentAdvantages } from "./TreatmentAdvantages";
export { TreatmentContent } from "./TreatmentContent";
export { TreatmentOverview } from "./TreatmentOverview";
export { TreatmentExpert } from "./TreatmentExpert";
export { TreatmentPricing } from "./TreatmentPricing";
export { TreatmentFAQ } from "./TreatmentFAQ";
export { TreatmentGlance } from "./TreatmentGlance";
export { TreatmentSimilar } from "./TreatmentSimilar";
export { TreatmentSpotlight } from "./TreatmentSpotlight";
export { RelatedBlogs } from "./RelatedBlogs";
export { BeforeAfterGallery } from "./BeforeAfterGallery";
export { BeforeAfterNav } from "./BeforeAfterNav";
export { TreatmentBeforeAfter } from "./TreatmentBeforeAfter";
export { TreatmentVideoTestimonials } from "./TreatmentVideoTestimonials";
export { TeamBioCarousel } from "./TeamBioCarousel";
export { TreatmentCTA } from "./TreatmentCTA";
export { TpIcon, glanceIconKey } from "./TpIcon";
export type { TreatmentMeta, GlanceItem, AdvantageItem, SimilarTreatmentItem, ReviewItem, BreadcrumbItem } from "./types";
